
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Brayan Adrian Galvan Flores || 181112
 */
public class RadioImagen extends javax.swing.JFrame {

    /**
     * Creates new form RadioImagen
     */
    public RadioImagen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbL = new javax.swing.JRadioButton();
        rbC = new javax.swing.JRadioButton();
        rbR = new javax.swing.JRadioButton();
        rbK = new javax.swing.JRadioButton();
        rbF = new javax.swing.JRadioButton();
        rbM = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rbL);
        rbL.setText("Linea");
        rbL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbC);
        rbC.setText("Circulo");
        rbC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbR);
        rbR.setText("Rectangulo");
        rbR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbK);
        rbK.setText("Koala");
        rbK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbF);
        rbF.setText("Faro");
        rbF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbM);
        rbM.setText("Medusa");
        rbM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(rbL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbM)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbL)
                    .addComponent(rbC)
                    .addComponent(rbR)
                    .addComponent(rbK)
                    .addComponent(rbF)
                    .addComponent(rbM))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRActionPerformed
        // TODO add your handling code here:
        Graphics papel = jPanel1.getGraphics();
        papel.setColor(Color.WHITE);
        papel.fillRect(10, 10, 300,250);
        papel.setColor(Color.red);
        if(rbR.isSelected()){
            papel.drawRect(50,50,200,200);
        }
    }//GEN-LAST:event_rbRActionPerformed

    private void rbLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLActionPerformed
        // TODO add your handling code here:
        Graphics papel = jPanel1.getGraphics();
        papel.setColor(Color.WHITE);
        papel.fillRect(10,10,300,250);
        papel.setColor(Color.red);
        if(rbL.isSelected()){
            papel.drawLine(50,50,200,200);
        }
    }//GEN-LAST:event_rbLActionPerformed

    private void rbCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCActionPerformed
        // TODO add your handling code here:
        Graphics papel = jPanel1.getGraphics();
        papel.setColor(Color.WHITE);
        papel.fillRect(10,10,300,250);
        papel.setColor(Color.red);
        if(rbC.isSelected()){
            papel.fillOval(50, 50, 200, 200);
        }
    }//GEN-LAST:event_rbCActionPerformed

    private void rbKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKActionPerformed
        // TODO add your handling code here:
        Graphics papel = jPanel1.getGraphics();
        papel.setColor(Color.WHITE);
        papel.fillRect(10,10,300,250);
        papel.setColor(Color.red);
        
        if(rbK.isSelected()){
            Image foto;
            foto = new ImageIcon("src/Imagen/Koala.jpg").getImage();
            papel.drawImage(foto, 10, 10, 300,200,null);
        }
    }//GEN-LAST:event_rbKActionPerformed

    private void rbFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFActionPerformed
        // TODO add your handling code here:
        Graphics papel = jPanel1.getGraphics();
        papel.setColor(Color.WHITE);
        papel.fillRect(10,10,300,250);
        papel.setColor(Color.red);
                
        if(rbF.isSelected()){
            Image foto;
            foto = new ImageIcon("src/Imagen/Faro.jpg").getImage();
            papel.drawImage(foto, 10, 10, 300,200,null);
        }
    }//GEN-LAST:event_rbFActionPerformed

    private void rbMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMActionPerformed
        // TODO add your handling code here:
        Graphics papel = jPanel1.getGraphics();
        papel.setColor(Color.WHITE);
        papel.fillRect(10,10,300,250);
        papel.setColor(Color.red);
        
        if(rbM.isSelected()){
            Image foto;
            foto = new ImageIcon("src/Imagen/Medusa.jpg").getImage();
            papel.drawImage(foto, 10, 10, 300,200,null);
        }
    }//GEN-LAST:event_rbMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioImagen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbC;
    private javax.swing.JRadioButton rbF;
    private javax.swing.JRadioButton rbK;
    private javax.swing.JRadioButton rbL;
    private javax.swing.JRadioButton rbM;
    private javax.swing.JRadioButton rbR;
    // End of variables declaration//GEN-END:variables
}
