
import java.awt.Color;
import java.awt.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Brayan Adrian Galvan Flores || 181112
 */
public class radioBoton extends javax.swing.JFrame {

    /**
     * Creates new form radioBoton
     */
    public radioBoton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        rbLinea = new javax.swing.JRadioButton();
        rbCirculo = new javax.swing.JRadioButton();
        rbRectangulo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGroup.add(rbLinea);
        rbLinea.setText("Linea");
        rbLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLineaActionPerformed(evt);
            }
        });

        btnGroup.add(rbCirculo);
        rbCirculo.setText("Circulo");
        rbCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCirculoActionPerformed(evt);
            }
        });

        btnGroup.add(rbRectangulo);
        rbRectangulo.setText("Rectagulo");
        rbRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRectanguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(rbLinea)
                .addGap(53, 53, 53)
                .addComponent(rbCirculo)
                .addGap(50, 50, 50)
                .addComponent(rbRectangulo)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLinea)
                    .addComponent(rbCirculo)
                    .addComponent(rbRectangulo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLineaActionPerformed
        // TODO add your handling code here:
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.white);
        papel.fillRect(0, 0, 400, 250);
        if(rbLinea.isSelected()){
            papel.setColor(Color.red);
            papel.drawLine(50, 50, 150, 150);
        }
    }//GEN-LAST:event_rbLineaActionPerformed

    private void rbCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCirculoActionPerformed
        // TODO add your handling code here:
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.white);
        papel.fillRect(0, 0, 400, 250);
        if(rbCirculo.isSelected()){
            papel.setColor(Color.red);
            papel.fillOval(50, 50, 150, 150);
        }
    }//GEN-LAST:event_rbCirculoActionPerformed

    private void rbRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRectanguloActionPerformed
        // TODO add your handling code here:
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.white);
        papel.fillRect(0, 0, 400, 250);
        if(rbRectangulo.isSelected()){
            papel.setColor(Color.red);
            papel.drawRect(50, 50, 150, 150);
        }
    }//GEN-LAST:event_rbRectanguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(radioBoton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(radioBoton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(radioBoton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(radioBoton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new radioBoton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton rbCirculo;
    private javax.swing.JRadioButton rbLinea;
    private javax.swing.JRadioButton rbRectangulo;
    // End of variables declaration//GEN-END:variables
}
