/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anama
 */
public class ModificacionFechas extends javax.swing.JFrame {

    /**
     * Creates new form ModificacionFechas
     */
    Date fechaP, fechaD,fechaNuevoPrestamo,fechaNuevaEntrega;
    String StringPrestamo,StringUsuario;
    int id_prestamo,dias,tipo,id_usuario;
    double multa;
    public ModificacionFechas() {
        initComponents();
       tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        modificar = new javax.swing.JTextField();
        retraso2 = new javax.swing.JRadioButton();
        retraso3 = new javax.swing.JRadioButton();
        retraso1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        regresar = new javax.swing.JButton();
        fecha = new javax.swing.JButton();
        retraso4 = new javax.swing.JRadioButton();
        retraso5 = new javax.swing.JRadioButton();
        retrasar6 = new javax.swing.JRadioButton();
        retrasar7 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libros96.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("El Futuro de Mexico FECHA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel2.setText("Ingrese el ID del prestamo a modificar");

        buttonGroup1.add(retraso2);
        retraso2.setText("Retrasar dos dias");
        retraso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retraso2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(retraso3);
        retraso3.setText("Retrasar tres dias");

        buttonGroup1.add(retraso1);
        retraso1.setText("Retrasar un dia");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_Prestamo", "ID_Usuario", "Multa", "Fecha de prestamo", "Fecha de devolucion"
            }
        ));
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setPreferredWidth(150);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(150);
            tabla.getColumnModel().getColumn(2).setPreferredWidth(200);
            tabla.getColumnModel().getColumn(3).setPreferredWidth(250);
            tabla.getColumnModel().getColumn(4).setPreferredWidth(250);
        }

        regresar.setBackground(new java.awt.Color(204, 255, 255));
        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return26.png"))); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        fecha.setBackground(new java.awt.Color(204, 255, 255));
        fecha.setText("Modificar Fecha");
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });

        buttonGroup1.add(retraso4);
        retraso4.setText("Retrasar cuatro dias");

        buttonGroup1.add(retraso5);
        retraso5.setText("Retrasar cinco dias");

        buttonGroup1.add(retrasar6);
        retrasar6.setText("Retrasar seis dias");

        buttonGroup1.add(retrasar7);
        retrasar7.setText("Retrasar siete dias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(retrasar7)
                                .addGap(220, 220, 220)
                                .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addGap(46, 46, 46))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(retraso1)
                                    .addComponent(retraso2)
                                    .addComponent(retraso3)
                                    .addComponent(retraso4)
                                    .addComponent(retraso5)
                                    .addComponent(retrasar6))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(retraso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(retraso2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(retraso3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(retraso4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(retraso5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(retrasar6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(retrasar7)
                            .addComponent(fecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retraso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retraso2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_retraso2ActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        MenuAdministrador m=new MenuAdministrador();
        m.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_regresarActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
        Excepciones excepcion=new Excepciones();
         String url = "jdbc:derby://localhost:1527/Biblioteca_Proyecto";
        String usuarioBD = "root";
        String passwordBD = "12345";
        boolean valida=true,boton=true,noLetras=true,encontrar=true;
        boolean noAdmi=true,noUser=true;
        
        try{
            StringPrestamo=modificar.getText();
            excepcion.campoVacio(StringPrestamo);
            if(StringPrestamo.matches("^[A-Za-z]*$")){
             JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
             noLetras=false;

           }
            id_prestamo=Integer.parseInt(StringPrestamo);
            //user
            

        }
        catch(Exception e){
            valida=false;
          JOptionPane.showMessageDialog(null, "No puede dejar campos vacios");

        }
        
        if(retraso1.isSelected()==false && retraso2.isSelected()==false && retraso3.isSelected()==false
          &&   retraso4.isSelected()==false && retraso5.isSelected()==false && retrasar6.isSelected()==false
                    && retrasar7.isSelected()==false){
            boton=false;
            JOptionPane.showMessageDialog(null, "Seleccione un boton");

        }
        
        
        
        if(valida==true && boton==true && noLetras==true){
            
            
            try{
             Connection conn = DriverManager.getConnection(url,usuarioBD,passwordBD);
            
             String querry3 = "SELECT ID_PRESTAMO FROM PRESTAMO WHERE ID_PRESTAMO = "+id_prestamo+"";
            Statement stsR = conn.createStatement();
            ResultSet rsQ = stsR.executeQuery(querry3);
             
             
                  if(rsQ.next()){
                 JOptionPane.showMessageDialog(null, "Prestamo encontrado!");

                   }
                  else{
                 JOptionPane.showMessageDialog(null, "No se encontro el prestamofdfs");
                 encontrar=false;
                  }
            
            String querry = "SELECT ID_PRESTAMO, FECHA_PRESTAMO,FECHA_ENTREGA FROM PRESTAMO WHERE ID_PRESTAMO = "+id_prestamo+"";
            Statement sts = conn.createStatement();
            ResultSet rs = sts.executeQuery(querry);
           
            
                  while(rs.next()){
                   fechaP= rs.getDate("FECHA_PRESTAMO");
                   fechaD =rs.getDate("FECHA_ENTREGA");
                 
                   dias = (int) ((fechaD.getTime()-fechaP.getTime())/86400000);
                  
                  }
            
                
            
            if(encontrar==true){
               
                
                 DateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
                if(noAdmi==true && noUser==true && multa ==0 ){
                    
               if(retraso1.isSelected()==true){
                  //Sumar dias a la fecha
                   //fechaNuevoPrestamo = new Date();
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(fechaP);
                    cal.add(Calendar.DATE,-1);
                    fechaP=cal.getTime();
                    
                     cal.setTime(fechaD);
                    cal.add(Calendar.DATE,-1);
                    fechaD=cal.getTime();
                    
                    
                    
                    String actualizar="UPDATE PRESTAMO SET FECHA_PRESTAMO =  '"+dateFormat.format(fechaP)+"', FECHA_ENTREGA = '"+dateFormat.format(fechaD)+"' WHERE ID_PRESTAMO = "+id_prestamo+"";
                    sts.executeUpdate(actualizar);
                    JOptionPane.showMessageDialog(null, "Modificacion de un dia realizada!" );
                    tabla();
                                     }  
              if(retraso2.isSelected()==true){
                  //Sumar dias a la fecha
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(fechaP);
                    cal.add(Calendar.DATE,-2);
                    fechaP=cal.getTime();
                    
                     cal.setTime(fechaD);
                    cal.add(Calendar.DATE,-2);
                    fechaD=cal.getTime();
                    
                   String actualizar="UPDATE PRESTAMO SET FECHA_PRESTAMO =  '"+dateFormat.format(fechaP)+"', FECHA_ENTREGA = '"+dateFormat.format(fechaD)+"' WHERE ID_PRESTAMO = "+id_prestamo+"    ";
                    sts.executeUpdate(actualizar);
                    JOptionPane.showMessageDialog(null, "Modificacion de dos realizada!" );
                    tabla();
              }  
                
              if(retraso3.isSelected()==true){
                  //Sumar dias a la fecha
                 
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(fechaP);
                    cal.add(Calendar.DATE,-3);
                    fechaP=cal.getTime();
                    
                     cal.setTime(fechaD);
                    cal.add(Calendar.DATE,-3);
                    fechaD=cal.getTime();
                    
                     String actualizar="UPDATE PRESTAMO SET FECHA_PRESTAMO =  '"+dateFormat.format(fechaP)+"', FECHA_ENTREGA = '"+dateFormat.format(fechaD)+"' WHERE ID_PRESTAMO = "+id_prestamo+"";
                    sts.executeUpdate(actualizar);
                    JOptionPane.showMessageDialog(null, "Modificacion de tres realizada!" );
                    tabla();
              }  
              if(retraso4.isSelected()==true){
                  //Sumar dias a la fecha
                 
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(fechaP);
                    cal.add(Calendar.DATE,-4);
                    fechaP=cal.getTime();
                    
                     cal.setTime(fechaD);
                    cal.add(Calendar.DATE,-4);
                    fechaD=cal.getTime();
                    
                     String actualizar="UPDATE PRESTAMO SET FECHA_PRESTAMO =  '"+dateFormat.format(fechaP)+"', FECHA_ENTREGA = '"+dateFormat.format(fechaD)+"' WHERE ID_PRESTAMO = "+id_prestamo+"";
                    sts.executeUpdate(actualizar);
                    JOptionPane.showMessageDialog(null, "Modificacion de tres realizada!" );
                    tabla();
              }  
              
              if(retraso5.isSelected()==true){
                  //Sumar dias a la fecha
                 
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(fechaP);
                    cal.add(Calendar.DATE,-5);
                    fechaP=cal.getTime();
                    
                     cal.setTime(fechaD);
                    cal.add(Calendar.DATE,-5);
                    fechaD=cal.getTime();
                    
                     String actualizar="UPDATE PRESTAMO SET FECHA_PRESTAMO =  '"+dateFormat.format(fechaP)+"', FECHA_ENTREGA = '"+dateFormat.format(fechaD)+"' WHERE ID_PRESTAMO = "+id_prestamo+"";
                    sts.executeUpdate(actualizar);
                    JOptionPane.showMessageDialog(null, "Modificacion de tres realizada!" );
                    tabla();
              }
              if(retrasar6.isSelected()==true){
                  //Sumar dias a la fecha
                 
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(fechaP);
                    cal.add(Calendar.DATE,-6);
                    fechaP=cal.getTime();
                    
                     cal.setTime(fechaD);
                    cal.add(Calendar.DATE,-6);
                    fechaD=cal.getTime();
                    
                     String actualizar="UPDATE PRESTAMO SET FECHA_PRESTAMO =  '"+dateFormat.format(fechaP)+"', FECHA_ENTREGA = '"+dateFormat.format(fechaD)+"' WHERE ID_PRESTAMO = "+id_prestamo+"";
                    sts.executeUpdate(actualizar);
                    JOptionPane.showMessageDialog(null, "Modificacion de tres realizada!" );
                    tabla();
              }  
              if(retrasar7.isSelected()==true){
                  //Sumar dias a la fecha
                 
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(fechaP);
                    cal.add(Calendar.DATE,-7);
                    fechaP=cal.getTime();
                    
                     cal.setTime(fechaD);
                    cal.add(Calendar.DATE,-7);
                    fechaD=cal.getTime();
                    
                     String actualizar="UPDATE PRESTAMO SET FECHA_PRESTAMO =  '"+dateFormat.format(fechaP)+"', FECHA_ENTREGA = '"+dateFormat.format(fechaD)+"' WHERE ID_PRESTAMO = "+id_prestamo+"";
                    sts.executeUpdate(actualizar);
                    JOptionPane.showMessageDialog(null, "Modificacion de tres realizada!" );
                    tabla();
              }  
                }
              
                
            }
            
            
                   System.out.println("Proceso terminado");
                sts.close();
                conn.close();
               
            }
                       
                catch (SQLException ex) {
                System.out.println("No se establecio conexion pa update: ");
                System.out.print(ex);
            
        } 
            
            
        }
        
        
             
        
    }//GEN-LAST:event_fechaActionPerformed
 public void tabla(){
          DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);

        int conta = 0;
        String url = "jdbc:derby://localhost:1527/Biblioteca_Proyecto";
        String usuarioBD = "root";
        String passwordBD = "12345";
        try(Connection conn = DriverManager.getConnection(url,usuarioBD,passwordBD)){
            String querry="SELECT * FROM PRESTAMO ";
            Statement sts = conn.createStatement();
            ResultSet rs = sts.executeQuery(querry);
            DefaultTableModel model= (DefaultTableModel)tabla.getModel();

            while(rs.next()){
                Vector v=new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                
                v.add(rs.getString(7));
                v.add(rs.getString(8));
               
                model.addRow(v);
                conta++;

            }

        }catch (SQLException ex) {
            System.out.println(ex.getNextException());
            System.out.println("No se establecio conexion");
            System.out.println(ex);
        }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificacionFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificacionFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificacionFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificacionFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificacionFechas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField modificar;
    private javax.swing.JButton regresar;
    private javax.swing.JRadioButton retrasar6;
    private javax.swing.JRadioButton retrasar7;
    private javax.swing.JRadioButton retraso1;
    private javax.swing.JRadioButton retraso2;
    private javax.swing.JRadioButton retraso3;
    private javax.swing.JRadioButton retraso4;
    private javax.swing.JRadioButton retraso5;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
